server:
  port: 8081
  jsp-servlet:
    init-parameters:
      development: true
  context-path: /Auction
spring:
  mvc:
    view:
      prefix: /
      suffix: .jsp
  http:
    multipart:
      max-file-size: 100Mb
      max-request-size: 10Mb
    encoding:
      charset: utf-8
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: yjs
    password: yjs
mybatis:
  type-aliases-package: com.baizhi.auction.entity
  mapper-locations: classpath:com.baizhi.auction.dao/*Mapper.xml